import { defineConfig } from "vite-plus";
import vue from "@vitejs/plugin-vue";
import { VitePWA } from "vite-plugin-pwa";
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { resolve, dirname } from "node:path";
import type { Plugin } from "vite";

// eslint-disable-next-line no-control-regex
const INVALID_CHAR_REGEX = /[\x00-\x1F\x7F<>*#"{}|^[\]`;?:&=+$,]/g;
const DRIVE_LETTER_REGEX = /^[a-z]:/i;

// ── Plugin manifest generator ──

function parseMetaFile(filePath: string) {
  const text = readFileSync(filePath, "utf-8");
  const dir = dirname(filePath).split(/[/\\]/).pop() ?? "";
  // Matches loadOn, pluginId, name, and optional formats
  const m = text.match(
    /loadOn\s*=\s*([^\n;]+).*?pluginId\s*=\s*"([^"]+).*?name\s*=\s*"([^"]+)(?:.*?formats\s*=\s*(\[[^\]]+\]))?/s,
  );
  if (!m) return null;
  let loadOn: string | string[] = m[1].replace(/\s*as\s+const\s*/g, "").trim();
  if (loadOn.startsWith("[")) loadOn = JSON.parse(loadOn.replace(/'/g, '"'));
  else loadOn = loadOn.replace(/["']/g, "");
  let formats: string[] | undefined;
  if (m[4]) {
    try {
      formats = JSON.parse(m[4].replace(/'/g, '"'));
    } catch {
      /* skip */
    }
  }
  return { pluginId: m[2], name: m[3], loadOn, dir, formats };
}

function pluginManifest(): Plugin {
  const GENERATED_FILE = "src/plugins/plugin-manifest.ts";

  return {
    name: "plugin-manifest",
    buildStart() {
      const root = process.cwd();
      const pluginsDir = resolve(root, "src/plugins");
      if (!existsSync(pluginsDir)) {
        this.warn("[plugin-manifest] src/plugins/ not found");
        return;
      }

      const entries: Array<{
        pluginId: string;
        name: string;
        loadOn: string | string[];
        dir: string;
        formats?: string[];
      }> = [];
      for (const item of readdirSync(pluginsDir)) {
        const itemPath = resolve(pluginsDir, item);
        const metaPath = resolve(pluginsDir, item, "meta.ts");
        if (statSync(itemPath).isDirectory() && existsSync(metaPath)) {
          const entry = parseMetaFile(metaPath);
          if (entry) entries.push(entry);
        }
      }
      entries.sort((a, b) => a.pluginId.localeCompare(b.pluginId));

      const code = [
        "// Auto-generated by vite-plugin-manifest. Do not edit.",
        "",
        "export interface PluginManifestEntry {",
        "  pluginId: string;",
        '  /** Scene(s) this plugin loads on — "app" | "book-import" | "bookshelf" | "reader" */',
        "  loadOn: string | string[];",
        "  name: string;",
        '  /** Directory name under src/plugins/, e.g. "annotations" */',
        "  dir: string;",
        "  /** File formats this plugin handles (parser plugins only) */",
        "  formats?: string[];",
        "}",
        "",
        `export const pluginManifest: PluginManifestEntry[] = ${JSON.stringify(entries, null, 2)};`,
        "",
      ].join("\n");

      const outPath = resolve(root, GENERATED_FILE);
      mkdirSync(dirname(outPath), { recursive: true });
      writeFileSync(outPath, code, "utf-8");
      this.info(`[plugin-manifest] Generated ${entries.length} entries → ${GENERATED_FILE}`);
    },
  };
}

// ── Config ──

export default defineConfig({
  plugins: [
    pluginManifest(),
    vue(),
    VitePWA({
      registerType: "autoUpdate",
    }),
  ],
  base: "/book/",
  server: {
    allowedHosts: true,
    proxy: {
      "/api": {
        target: "http://localhost:3001",
        changeOrigin: true,
      },
    },
  },
  test: {
    environment: "happy-dom",
  },
  staged: {
    "*": "vp check --fix",
  },
  lint: {
    options: {
      typeAware: true,
      typeCheck: true,
    },
    ignorePatterns: ["server/**"],
  },
  build: {
    rolldownOptions: {
      output: {
        sanitizeFileName(name: string): string {
          const match = DRIVE_LETTER_REGEX.exec(name);
          const driveLetter = match ? match[0] : "";
          return driveLetter + name.slice(driveLetter.length).replace(INVALID_CHAR_REGEX, "");
        },
      },
    },
  },
});
